spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: ~/h2/account-api
    username: sa
    password:

logging:
  level:
    p6spy: info